# Dependencies
markdown:       kramdown
highlighter:    rouge

kramdown:
  auto_ids:           true
  syntax_highlighter: rouge

# Permalinks
permalink:      pretty

# Server
source:         "."
url:            "https://www,sproutfund.org"
baseurl:        "/"
encoding:       UTF-8
exclude:
  - CNAME
  - .bundle/
  - .git/
  - .github/
  - _vendor/
  - _assets_src/
  - _photos_src/
  - node_modules/
  - CODE_OF_CONDUCT.md
  - composer.json
  - Gemfile
  - Gemfile.lock
  - package.js
  - package.json
  - package-lock.json
  - README.md
  - LICENSE.md
  - TO-DO.md
  - sache.json
  - twbsconfig.yml
  - scripts
  - "*.bak"
  - search/data_projects.json
  - search/data_programs.json
  - test.md
  - year/

keep_files:
  - assets/brand/
  - assets/fonts/
  - assets/img/
  - assets/js/
  - downloads/
  - photos/
  - videos/
  - theme/

plugins:
  - github-pages
#  - jekyll-github-metadata
  - jekyll-redirect-from
#  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji

# Github
repository: sproutfund/website_evergreen

# Social
title:              "The Sprout Fund"
description:        "Communities are better places to live, learn, and thrive because of the people and ideas supported by The Sprout Fund."
twitter:            sproutfund
authors:            "The Sprout Fund"
social_image_path:  /assets/brand/sproutfund-in-circle_social-square.png
social_logo_path:   /assets/brand/sproutfund-in-circle_social-wide.png

# Custom variables
repo:               "https://github.com/sproutfund/website_evergreen"

cdn:
  # See https://www.srihash.org for info on how to generate the hashes
#  bootstrap_css:      "https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css"
#  bootstrap_css_hash: "sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB"
#  bootstrap_js:       "https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"
#  bootstrap_js_hash:  "sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T"
#  jquery:             "https://code.jquery.com/jquery-3.3.1.slim.min.js"
#  jquery_hash:        "sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"

relative_links:
  enabled:     true
  collections: false

sass:
  sass_dir: _sass
  style: compressed
